project:
  type: website

website:
  title: StatCan RTO
  favicon: /images/RTO.png
  navbar:
    title: StatCan RTO
    search: true
    left:
      - text: "English"
        href: main_en.qmd
      - text: "Français"
        href: main_fr.qmd
  sidebar:
    - title: "English"
      style: "docked"
      logo: /images/RTO.png
      logo-href: main_en.qmd
      contents:
      - href: main_en.qmd
        text: Call to Action
      - href: bkgrd_en.qmd
        text: Backgrounds
      - href: faq_en.qmd
        text: FAQ

    - title: "Français"
      contents:
      - href: main_fr.qmd
        text: Appel à l'action
      - href: bkgrd_fr.qmd
        text: Arrière-plans
      - href: faq_fr.qmd
        text: FAQ

format:
  html:
    theme: [superhero, theme.scss]
    css: styles.css
    backgroundcolor:  rgb(8, 84, 0)
    fontsize: 1.5em
    linestretch: 1.2
    toc: true