---
title: "Foire aux questions (FAQ)"
navbar: false
---

<link rel="stylesheet" href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css><button onclick="window.location = location.href.replace('fr','en');" class="btn"><i class="fa fa-language"></i> English</button>

Veuillez envoyer vos questions à [RTO.LOC.503@gmail.com](mailto:RTO.LOC.503@gmail.com). Nous ajouterons des informations supplémentaires au fur et à mesure que nous recevrons des questions.

## Dois-je renouveler mon entente dans mesRégimesDeTravail ?

Oui. Si vous n'avez pas d'accord de télétravail actif, l'employeur peut insister pour que vous travailliez au bureau 5 jours par semaine. La signature d'un accord de télétravail ne limite pas votre capacité à demander un nouvel accord de télétravail à l'avenir.

## Est-ce que je subirai des répercussions négatives en signant la pétition ?

Non, vous ne devriez subir aucune répercussion, et vous pouvez signer la pétition sans crainte. La signature de cette pétition ne contrevient pas au Code de valeurs et d’éthique du Conseil du Trésor et ne constitue pas un motif de sanction. C’est votre droit en tant que personne et en tant qu’employé·e. Si vous subissez une quelconque répercussion, n’hésitez pas à contacter votre délégué·e syndical·e. ([Source d'information](https://pipsc.ca/fr/nouvelles-et-enjeux/retour-sur-le-lieu-de-travail/faq-retour-sur-le-lieu-de-travail))