---
title: "Appel à l'action"
---

**Ensemble, nous pouvons rester fermes sur cette question du télétravail.**

Le mois de septembre approche, tout comme la mise en œuvre de la directive sur la présence prescrite sur le lieu de travail - 3 jours au bureau et la fin des bureaux permanents pour ceux qui travaillent au bureau à plein temps. 

**Il est temps de s'organiser !**

**Il est temps de s'opposer au retour forcé au bureau !**

## Voici ce que vous pouvez faire dès maintenant :

### 1. Rejoindre le Comité

Bien que coprésidé par des membres de l'ACEP, ce comité sur le télétravail est ouvert à tous les employés de Statistique Canada.

Veuillez remplir ce formulaire pour rejoindre le Comité :

Nous cherchons à rejoindre le plus grand nombre de personnes possible au cours des prochaines semaines afin de bâtir un réseau solide à StatCan. 

### 2. Diffuser le message

Partagez cette page web avec au moins deux amis ou collègues de Statistique Canada que vous savez intéressés par la lutte contre le retour forcé au bureau, en leur demandant de remplir le formulaire. 

### 3. Pétition - bientôt disponible !

Restez à l’écoute des prochaines étapes.
