---
title: "Call to Action"
---

**Together, we can stand firm on the issue of telework.**

September approaches and so does the implementation of the Direction on Prescribed Workplace Presence - 3 Days in office and the end of permanent desks for those working in office fulltime. 

**It’s time to get organized!**

**It's time to push back against the forced return-to-office!**

## Here is what you can do right now:

### 1. Join the Telework Rights Committee

While co-chaired by CAPE members, this Telework Committee is open to all Statistics Canada employees.

Please fill out this form to join the Committee:

We are looking to reach as many people as possible in the coming weeks to build a strong network at StatCan.

### 2. Spread the Word

Share this webpage with at least two friends or colleagues at Statistics Canada that you know are interested in pushing back against the forced return-to-office. Ask them to fill out the form.

### 3. Petition - coming soon!

Stay tuned for next steps.
