---
title: "StatCan Telework Rights Campaign"
navbar: false
lang: en
---

<link rel="stylesheet" href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css><button onclick="window.location = location.href.replace('en','fr');" class="btn"><i class="fa fa-language"></i> Français</button>

**Together, we can stand firm on the issue of telework.**

Now that the implementation of the Direction on Prescribed Workplace Presence is in place - 3 Days in office and the end of permanent desks for those working in office fulltime, it's time to do something about it!

**It’s time to get organized!**

## Here is what you can do right now:

### 1. Sign the Petition!

[Click here to read and sign the StatCan petition!!](https://docs.google.com/forms/d/e/1FAIpQLSc941-n5h6onnS_EVO-385bY1M_QvIv_UNhUeKMjeap1Bgu7g/viewform)

[If you're not a StatCan employee but are in the federal public service employee, click here to find the petition specific to your department](https://www.acep-cape.ca/en/links-petitions)

For more information on risk, see [Petition risk mitigation](risk_en.qmd#petition)

### 2. Spread the Word

Share this webpage with at least two friends or colleagues at Statistics Canada and ask them to sign the petition!

For information on mitigating risk while discussing union activities in the workplace see [risk mitgation while spreading the word](risk_en.qmd#spreading-the-word)

### 3. Join the Statistics Canada Telework Rights Campaign

While launched by CAPE members, the Telework Rights Campaign is open to all Statistics Canada employees.

[Please fill out this form to join the Campaign](https://docs.google.com/forms/d/e/1FAIpQLScDAxDiH4Hb1j4zuykaBMIzBHtGuhvjCXEn0jVbRPrMXxaDGQ/viewform?usp=sf_link)

We are looking to reach as many people as possible in the coming weeks to build a strong network at StatCan.

Stay tuned for next steps.

## Upcoming actions:

### 1. 'Remote Works' backgrounds

Start using one of our ['Remote Works' backgrounds](bkgrd_en.qmd) on Microsoft teams starting September 3rd

### 2.  Report unsuitable work space in office

Couldn’t find a suitable workspace at the office? [Let us know in this form!](https://forms.gle/ncAz94YuQWxEQ2dG7)

## Contact us

You can contact your coworkers who are coordinating this campaign at: [RTO.LOC.503@gmail.com](mailto:RTO.LOC.503@gmail.com)

