---
title: "Campagne sur le droit au télétravail"
navbar: false
lang: fr
---

<link rel="stylesheet" href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css><button onclick="window.location = location.href.replace('fr','en');" class="btn"><i class="fa fa-language"></i> English</button>

**Ensemble, nous pouvons rester fermes sur cette question du télétravail.**

Maintenant que la mise en œuvre de la directive sur la présence prescrite sur le lieu de travail est en place - 3 jours au bureau et la fin des bureaux permanents pour ceux qui travaillent au bureau à plein temps, il est temps de faire quelque chose !

**Il est temps de s'organiser !**

## Voici ce que vous pouvez faire dès maintenant :

### 1. Signez la pétition !

[Cliquez ici pour lire et signer la pétition!!](https://docs.google.com/forms/d/e/1FAIpQLSc941-n5h6onnS_EVO-385bY1M_QvIv_UNhUeKMjeap1Bgu7g/viewform)

[Si vous n'êtes pas un employé de StatCan mais que vous faites partie de la fonction publique fédérale, cliquez ici pour trouver la pétition spécifique à votre ministère](https://www.acep-cape.ca/fr/liens-vers-les-petitions)

Pour plus d'informations sur la manière dont nous atténuons les risques liés à cette pétition, voir [Atténuation des risques liés à la pétition](risk_fr.qmd#pétition)

### 2. Diffuser le message

Partagez cette page web avec au moins deux amis ou collègues de Statistique Canada, et demandez-leur de signer la pétition.

Pour plus d'informations sur l'atténuation des risques lors de la discussion des activités syndicales sur le lieu de travail, voir [atténuation des risques lors de la diffusion de l'information](risk_fr.qmd#faire-passer-le-message)

### 3. Rejoignez la campagne sur le droit au télétravail de Statistique Canada !

Bien que lancée par les membres de l'ACEP, la campagne sur le droit au télétravail est ouverte à tous les employés de Statistique Canada.

[Veuillez remplir ce formulaire pour vous joindre à la campagne](https://docs.google.com/forms/d/e/1FAIpQLScDAxDiH4Hb1j4zuykaBMIzBHtGuhvjCXEn0jVbRPrMXxaDGQ/viewform?usp=sf_link)

Nous cherchons à rejoindre le plus grand nombre de personnes possible au cours des prochaines semaines afin de bâtir un réseau solide à StatCan. 

Restez à l’écoute des prochaines étapes.

## Actions à venir :

### 1. Arrière-plans 'Ça travaille à distance !'

Commencez à utiliser l'un de nos [arrière-plans 'Ça travaille à distance !'](bkgrd_fr.qmd) dans les équipes Microsoft à partir du 3 septembre.

### 2.  Signaler un espace de travail inadapté au bureau

Vous n’avez pas trouvé d’espace de travail approprié au bureau ? [Dites-le-nous dans ce formulaire !](https://forms.gle/ncAz94YuQWxEQ2dG7)

## Contactez-nous

Vous pouvez contacter vos collègues qui coordonnent cette campagne à l'adresse suivante : [RTO.LOC.503@gmail.com](mailto:RTO.LOC.503@gmail.com)