---
title: "Risk Mitigation"
---

<link rel="stylesheet" href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css><button onclick="window.location = location.href.replace('en','fr');" class="btn"><i class="fa fa-language"></i> Français</button>

# Union & political activities in the workplace

There are no simple answers to the question of what union or political actions you can safely take in the workplace as a federal public servant. The risk evaluation and mitigation information, which is compiled here, is based on legal battles that unions have fought in the past to defend employees whom the employer has tried to discipline for union or political activities. 

Our employer has a material interest in limiting what we do in this fight for telework rights. <u>**It is in the employer's best interest to spread misinformation, in order to frighten us into inaction.**</u> Even if we legally prove such actions have violated our rights as employees; time will have passed, and we'll be past the important organizing moment. Some departments are already reporting that senior management has been telling staff that signing petitions or wearing buttons is a breach of the values and ethics code. That is false. Unfortunately we should expect to see similar misinformation spread here.

Even with the highest risk actions, <u>**risk can be reduced by acting together**</u>. This was well demonstrated when [Ontario education workers won big wins through an “illegal” wildcat strike in 2022](https://www.cbc.ca/news/canada/toronto/ont-government-repeals-education-bill-1.6650584).
Wildcat strikes are one of the highest risk tools available to workers, and it only worked for them because they were able to act in unity. Note: We are not advocating for a wildcat strike.

All of that being said, <u>**don't take risks without strategic reason!**</u> While the situation can be frustrating at times, keep a cool head and stick to the plan and let's fight this together!

## General Guidelines

Public Servants have a chartered right to freedom of speech. However, this is considered in balance with two duties that public servants are bound by:

* Loyalty to their employer (Government of Canada)
* Impartiality to the public at large (and the appearance of impartiality)

Expressing ideas that are not in alignment with government policy can in some circumstances be considered to breach these duties. To evaluate and mitigate your risk in taking action, ask yourself the following questions:

* [Who is seeing the message?](#who-is-seeing-the-message)
* [How is the message framed?](#how-is-the-message-framed)
* [What is the medium of the message?](#what-is-the-medium-of-the-message)
* [Who is sending the message?](#who-is-sending-the-message)


### Who is seeing the message?

Public servants have more leeway in expressing their opinions around colleagues in the public service as opposed to expressing opinions to third party contractors, external clients or the public at large. This is why we recommend taking off campaign buttons, and not using campaign video backgrounds when speaking with external clients or the public. This is also a good reason to avoid social media posts, speaking with the media, or speaking at rallies.

### How is the message framed?

Frame your messaging in support of something as opposed to directly criticising government policy. For example, it is safer to say “I want telework rights!” than to say “I think the policy on prescribed presence in the workplace is incompetent.” (examples are of course for illustrative purposes only).

### What is the medium of the message?

Using the employer’s systems, assets and tools is higher risk. This is both because they have some right to dictate how you use their tools, and because they can see your messaging. This would include putting up posters in the office, using your out of office auto-reply message, using work email & MS teams to communicate, and using MS teams video backgrounds. We recommend you not discuss this campaign using work email, and that if you use teams messages you keep the messages simple (ex. “can we meet to chat about RTO on your next break?”). For information on risk mitigation when using MS teams backgrounds see [backgrounds](#backgrounds).

### Who is sending the message?

Your role in the public service affects how your actions affect public perceptions of impartiality. You may be at higher risk if you:

* Are very visible publicly
* Have more authority in your role at work
* Are in a role that is tied to the topic (ie. your role is directly tied to implementation of RTO)

## Risk mitigation by action

### Petition 
Signing the petition is one of the safest ways you can take part and here is why:

This is a majority petition, that means we will not be delivering the petition until a majority have signed it. It's very difficult for the employer to discipline the majority of their staff. 

<u>For CAPE members:</u>

We will not deliver your signatures until after we either have signatures from the majority of StatCan CAPE members, or signatures from the majority of union members at statcan under the following unions (CAPE, PIPSC, PSAC, & ACFO)

<u>For PIPSC, PSAC & ACFO members:</u>

While this petition is being managed by CAPE, the decision as to when to deliver the signatures from PIPSC, PSAC & ACFO members will be up to those who are coordinating from those unions. We will update this page with details soon.

### Spreading the word

You have the right to discuss the petition and other actions with your coworkers. What you don't have a right to, is doing this during work hours or using the employer's software. Because of this we recommend you have these discussions with your coworkers verbally (including an MS Teams call), or through non-work channels and on break time or lunch hour other non working times. You can use MS Teams or work email to ask your coworkers if they would be available to chat or call on their next break/lunch to set up these conversations.

### Backgrounds 

Using a telework campaign MS teams background is a higher risk action, please consider the following ways to limit your risk:

1. If you're asked to take the background down, do so! It is easier for the employer to discipline you for not following a direction to take it down than to discipline you for putting it up in the first place. If you're asked to take it down we encourage you to follow up with an email asking for an explanation of why you you were asked to take it down and clarification as to the limitations on what you can use as a teams background going forward and share the responses with us at [RTO.LOC.503@gmail.com](mailto:RTO.LOC.503@gmail.com)
1. Do not use these backgrounds for meetings with external clients.
1. Coordinate with others in your unit and division. It will make a bigger impact if many of you start using the backgrounds at the same time, and there is always more safety in numbers.
1. If you're asked to take these backgrounds down, or just want a less risky way to take part, consider using the generic green background. Green is the colour the unions have agreed on for the telework rights fight. Imagine the visual impact of a division wide meeting where 70% of people have a solid green background.

### Attending Rallies

Attending a rally is a very low risk action. Your risk increases if:

* You’re carrying a sign, how much additional risk depends on the content of the sign
* You give a speech
* You speak to the media (please don't speak to the media. All telework rallies should have have a designated media spokesperson who will handle any media questions)
* You stay at a rally after the messaging becomes problematic (Case law was around public servants at the convoy protests)
